# general content

title: Ladiëresis
email: info@ladieresis.net
description: > # this means to ignore newlines until "baseurl:"
   Creer es crear
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ladieresis-net" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock

# Sass settings

sass:
  sass_dir: _scss
  style: :compressed

# Gems

gems:
  - jekyll-feed